// <auto-generated />
using System;
using GuestbookData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuestbookData.Migrations
{
    [DbContext(typeof(GuestbookDbContext))]
    [Migration("20211110123319_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuestbookData.Model.GuestbookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GuestbookEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Awesome site bro, but I don't like the background that much.",
                            Email = "adam@gmail.com",
                            Name = "Adam",
                            Timestamp = new DateTime(2021, 11, 9, 23, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Umm... where do I submit the post?",
                            Email = "bernard@yahoo.com",
                            Name = "Bernard",
                            Timestamp = new DateTime(2021, 11, 9, 22, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Comment = "We work so hard to deliver all these awesome software and people use it to make stuff like this -_-",
                            Email = "cecilia@microsoft.com",
                            Name = "Cecilia",
                            Timestamp = new DateTime(2021, 11, 9, 21, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Comment = "I was here and found your interface inadequate.",
                            Email = "dick@gmail.com",
                            Name = "Dick",
                            Timestamp = new DateTime(2021, 11, 9, 20, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Lovely site, keep it going!",
                            Email = "ernest@aol.com",
                            Name = "Ernest",
                            Timestamp = new DateTime(2021, 11, 9, 19, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Comment = "ಠ_ಠ ಠ_ಠ ಠ_ಠ ಠ_ಠ ಠ_ಠ ಠ_ಠ",
                            Email = "filip@gmail.com",
                            Name = "Filip",
                            Timestamp = new DateTime(2021, 11, 9, 21, 0, 0, 0, DateTimeKind.Local)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
